# Generated by Django 4.0.5 on 2022-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_driver_liscence_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='police_record',
            field=models.ImageField(default='none', upload_to='policeRecord'),
            preserve_default=False,
        ),
    ]
