# Generated by Django 4.0.5 on 2022-06-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('seats_booked', models.CharField(max_length=255)),
            ],
        ),
    ]
