# Generated by Django 4.0.5 on 2022-06-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_persondriver_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondriver',
            name='person_address',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persondriver',
            name='person_pickup_Time',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
