# Generated by Django 4.0.5 on 2022-06-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_persondriver_person_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondriver',
            name='driver_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='persondriver',
            name='person_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
