# Generated by Django 4.0.5 on 2022-06-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_persondriver_driver_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondriver',
            name='driver_location',
            field=models.CharField(blank=True, default='32.4945,74.5229', max_length=255),
        ),
        migrations.AlterField(
            model_name='persondriver',
            name='person_location',
            field=models.CharField(blank=True, default='32.4945,74.5229', max_length=255),
        ),
    ]
